In [ ]:
Fraud Detection using Transaction Behavior Analysis

This project identifies suspicious transactions based on abnormal spending patterns.

Logic used:
- Transactions above normal threshold flagged
- Behavioral condition (time) added to improve accuracy

Result:
- Reduced alerts from 97 to 81 using refined rules

In [1]:
import pandas as pd

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df['total_bill'].head()

0    16.99
1    10.34
2    21.01
3    23.68
4    24.59
Name: total_bill, dtype: float64

In [19]:
df['total_bill'].mean()

19.785942622950824

In [20]:
df['total_bill'] / df['total_bill'].mean()

0      0.858690
1      0.522593
2      1.061865
3      1.196809
4      1.242802
         ...
239    1.467203
240    1.373703
241    1.145763
242    0.900639
243    0.949159
Name: total_bill, Length: 244, dtype: float64

In [21]:
(df['total_bill'] / df['total_bill'].mean()) > 1.2

0      False
1      False
2      False
3      False
4       True
       ...
239     True
240     True
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [22]:
df[df['total_bill'] > df['total_bill'].mean() * 1.2]

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,False
5,25.29,4.71,Male,No,Sun,Dinner,4,1.278180,False
7,26.88,3.12,Male,No,Sun,Dinner,4,1.358540,False
11,35.26,5.00,Female,No,Sun,Dinner,4,1.782073,True
23,39.42,7.58,Male,No,Sat,Dinner,4,1.992324,True
...,...,...,...,...,...,...,...,...,...
230,24.01,2.00,Male,Yes,Sat,Dinner,4,1.213488,False
237,32.83,1.17,Male,Yes,Sat,Dinner,2,1.659259,True
238,35.83,4.67,Female,No,Sat,Dinner,3,1.810882,True
239,29.03,5.92,Male,No,Sat,Dinner,3,1.467203,False
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1.373703,False

In [26]:
df['total_bill'].max()

50.81

In [27]:
df['total_bill'].mean()

19.785942622950824

In [28]:
df[df['total_bill'] > 20]

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,False
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,False
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True
5,25.29,4.71,Male,No,Sun,Dinner,4,1.278180,True
7,26.88,3.12,Male,No,Sun,Dinner,4,1.358540,True
...,...,...,...,...,...,...,...,...,...
237,32.83,1.17,Male,Yes,Sat,Dinner,2,1.659259,True
238,35.83,4.67,Female,No,Sat,Dinner,3,1.810882,True
239,29.03,5.92,Male,No,Sat,Dinner,3,1.467203,True
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1.373703,True
241,22.67,2.00,Male,Yes,Sat,Dinner,2,1.145763,False

In [31]:
df[df['total_bill'] > 20].head()

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,True
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True
5,25.29,4.71,Male,No,Sun,Dinner,4,1.278180,True
7,26.88,3.12,Male,No,Sun,Dinner,4,1.358540,True

In [32]:
(df['total_bill'] > 20).sum()

97

In [39]:
'suspicious' in df.columns

True

In [40]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious
0,16.99,1.01,Female,No,Sun,Dinner,2,0.858690,False
1,10.34,1.66,Male,No,Sun,Dinner,3,0.522593,False
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,True
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True

In [41]:
df['suspicious'].value_counts()

False    147
True      97
Name: suspicious, dtype: int64

In [42]:
df[df['suspicious'] == True].head()

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,True
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True
5,25.29,4.71,Male,No,Sun,Dinner,4,1.278180,True
7,26.88,3.12,Male,No,Sun,Dinner,4,1.358540,True

In [45]:
df['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [48]:
df[df['time'] == 'Dinner'].head()

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious,final_flag
0,16.99,1.01,Female,No,Sun,Dinner,2,0.858690,False,False
1,10.34,1.66,Male,No,Sun,Dinner,3,0.522593,False,False
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,True,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,True,True
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True,True

In [53]:
((df['total_bill'] > 20) & (df['time'] == 'Dinner')).sum()

81

In [55]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,amount_ratio,suspicious,final_flag
0,16.99,1.01,Female,No,Sun,Dinner,2,0.858690,False,False
1,10.34,1.66,Male,No,Sun,Dinner,3,0.522593,False,False
2,21.01,3.50,Male,No,Sun,Dinner,3,1.061865,True,True
3,23.68,3.31,Male,No,Sun,Dinner,2,1.196809,True,True
4,24.59,3.61,Female,No,Sun,Dinner,4,1.242802,True,True

In [56]:
df['final_flag'].value_counts()

False    163
True      81
Name: final_flag, dtype: int64